### ISSUE TITLE
Tidy up the PostController and make code easier to read

### ISSUE THREAD

**Issue by ryangjchandler** [damcclean/duncanm.dev#7]
https://github.com/damcclean/duncanm.dev/blob/d40df80e26aad88b9d9accfa89b6efae5f3d5d69/app/Http/Controllers/PostController.php#L14-L20

Couple of ways to clean this code up:

1. Change `if (auth()->user() != null)` to `if(auth()->check())`

2. Possibly change the `published()` and `includeDraft()` to a single global scope on the Post model that handles the authentication checks.

**Comment by damcclean** [comment]
If I was to go down the option of a global scope on the `Post` model, wouldn't I just need to do the same kind of stuff there?

**Comment by ryangjchandler** [comment]
Yeah, you would do the same stuff there but then you have a single place responsible for that logic. If you created multiple places for posts, you would need to copy and paste the logic each time, instead of having a single global scope.
